// Bundled sample so the shell renders in a plain browser (no Tauri).
// Mirrors examples/isgd-tci in the repo.

import type { Project } from "./backend";

const root = "/examples/isgd-tci";

export const SAMPLE_FILES: Record<string, string> = {
  [`${root}/main.tex`]: `\\documentclass[journal]{IEEEtran}
\\usepackage{amsmath,amssymb,graphicx,booktabs}
\\newcommand{\\norm}[1]{\\left\\lVert #1 \\right\\rVert}

\\title{Injective Sampling for Generative Diffusion Priors in Computational Imaging}
\\author{Sadegh Salehi \\and Marta Ruiz}

\\begin{document}
\\maketitle

\\begin{abstract}
We study when a masked measurement operator admits a unique reconstruction under a diffusion prior. We give a density condition on the mask that guarantees injectivity on band-limited signals, and show that a lightweight guidance term recovers a 1.8 dB margin over three baselines across noise levels up to $\\sigma = 0.3$.
\\end{abstract}

\\section{Introduction}
Reconstructing an image from incomplete measurements is ill-posed unless the prior is strong enough to close the gap left by the sampling operator~\\cite{candes2006,ho2020ddpm}. Recent work uses diffusion models as that prior, but says little about \\emph{when} the forward map itself leaves enough information to recover a unique signal.

\\section{Method}
\\subsection{Forward model}
Let $x \\in \\mathbb{R}^n$ be the unknown image and $A = M F$ the operator formed by a Fourier transform $F$ followed by a binary mask $M$. We observe $y = A x + \\eta$ with $\\eta \\sim \\mathcal{N}(0, \\sigma^2 I)$.

\\subsection{Injectivity of the forward map}
We show that the sampling operator is injective on the class of band-limited signals when the mask satisfies the density condition below.
\\begin{equation}
  \\norm{A x}_2 \\ge c \\, \\norm{x}_2 \\quad \\text{for all } x \\in B_\\Omega
  \\label{eq:injective}
\\end{equation}
The constant $c$ depends only on the mask density and the bandwidth $\\Omega$; see Appendix~A for the proof. Equation~\\eqref{eq:injective} is what lets the guidance term in Section~\\ref{sec:guidance} stay well-conditioned.

\\subsection{Guided sampling}
\\label{sec:guidance}
At each reverse step we add a data-consistency gradient scaled by the injectivity constant. Figure~\\ref{fig:psnr} reports PSNR against noise level for three baselines; the proposed method holds a 1.8 dB margin up to $\\sigma = 0.3$.

\\begin{figure}[t]
  \\centering
  \\includegraphics[width=\\linewidth]{figures/psnr-vs-noise.pdf}
  \\caption{PSNR against noise level $\\sigma$ on the fastMRI knee subset. Shaded bands are one standard deviation over five seeds.}
  \\label{fig:psnr}
\\end{figure}

\\section{Results}
\\input{tables/psnr-sweep}
Across all noise levels the proposed sampler is the only method whose reconstructions remain sharp at $\\sigma = 0.3$~\\cite{chung2023dps}.

\\section{Conclusion}
A density condition on the mask is enough to make diffusion-guided reconstruction well-posed; the code and the sweep that produced every figure are in the repository.

\\bibliographystyle{IEEEtran}
\\bibliography{refs}
\\end{document}
`,
  [`${root}/refs.bib`]: `@article{candes2006,
  title={Robust uncertainty principles},
  author={Cand\\\`es, Emmanuel and Romberg, Justin and Tao, Terence},
  journal={IEEE Trans. Inf. Theory}, year={2006}
}
@inproceedings{ho2020ddpm,
  title={Denoising diffusion probabilistic models},
  author={Ho, Jonathan and Jain, Ajay and Abbeel, Pieter},
  booktitle={NeurIPS}, year={2020}
}
@inproceedings{chung2023dps,
  title={Diffusion posterior sampling for general noisy inverse problems},
  author={Chung, Hyungjin and others},
  booktitle={ICLR}, year={2023}
}
`,
  [`${root}/code/sweep.py`]: `"""Noise sweep that produces figures/psnr-vs-noise.pdf and tables/psnr-sweep.tex."""
import argparse
import numpy as np

def main(sigma_max: float, seeds: int = 5):
    sigmas = np.linspace(0.0, sigma_max, 7)
    # ... run reconstruction for each sigma and seed ...
    print(f"swept {len(sigmas)} noise levels x {seeds} seeds")

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--sigma", type=float, default=0.2)
    main(p.parse_args().sigma)
`,
  [`${root}/tables/psnr-sweep.tex`]: `\\begin{table}[t]
\\caption{PSNR (dB) by noise level. Generated by code/sweep.py; do not edit by hand.}
\\begin{tabular}{lccc}
\\toprule
$\\sigma$ & DPS & Baseline B & Ours \\\\
\\midrule
0.1 & 31.2 & 30.8 & 33.0 \\\\
0.2 & 28.9 & 28.1 & 30.7 \\\\
0.3 & 25.4 & 24.6 & 27.2 \\\\
\\bottomrule
\\end{tabular}
\\end{table}
`,
};

export const SAMPLE_PROJECT: Project = {
  root,
  name: "isgd-tci",
  mainTex: `${root}/main.tex`,
  hasGit: true,
  hasMemory: true,
  tree: [
    { name: "code", path: `${root}/code`, kind: "dir", children: [
      { name: "sweep.py", path: `${root}/code/sweep.py`, kind: "code", children: [] },
    ]},
    { name: "figures", path: `${root}/figures`, kind: "dir", children: [
      { name: "psnr-vs-noise.pdf", path: `${root}/figures/psnr-vs-noise.pdf`, kind: "figure", children: [] },
    ]},
    { name: "tables", path: `${root}/tables`, kind: "dir", children: [
      { name: "psnr-sweep.tex", path: `${root}/tables/psnr-sweep.tex`, kind: "tex", children: [] },
    ]},
    { name: "dabir.toml", path: `${root}/dabir.toml`, kind: "data", children: [] },
    { name: "main.tex", path: `${root}/main.tex`, kind: "tex", children: [] },
    { name: "refs.bib", path: `${root}/refs.bib`, kind: "bib", children: [] },
  ],
};
