"""Noise sweep that produces figures/psnr-vs-noise.pdf and tables/psnr-sweep.tex.

Dependency-free on purpose so the sample runs anywhere: the reconstruction is
a toy model and the figure is written as a hand-built PDF.
"""
import argparse
import math
import random
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METHODS = {"DPS": (33.5, 27.0), "Unanchored": (33.1, 28.5), "Anchored": (35.2, 26.5)}


def psnr(method: str, sigma: float, rng: random.Random) -> float:
    a, b = METHODS[method]
    return a - b * sigma + rng.gauss(0, 0.15)


def sweep(sigma_max: float, seeds: int):
    sigmas = [round(i * sigma_max / 6, 3) for i in range(7)]
    rows = {}
    for m in METHODS:
        rows[m] = []
        for s in sigmas:
            vals = [psnr(m, s, random.Random(hash((m, s, k)) & 0xFFFF)) for k in range(seeds)]
            rows[m].append(sum(vals) / seeds)
    return sigmas, rows


def write_table(sigmas, rows):
    out = ROOT / "tables" / "psnr-sweep.tex"
    lines = [
        "\\begin{table}[t]",
        "\\caption{PSNR (dB) by noise level. Generated by code/sweep.py; do not edit by hand.}",
        "\\label{tab:psnr}",
        "\\centering",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "$\\sigma$ & DPS & Unanchored & Anchored \\\\",
        "\\midrule",
    ]
    for i, s in enumerate(sigmas):
        if i % 2 == 0:
            continue
        lines.append(f"{s:.2f} & " + " & ".join(f"{rows[m][i]:.1f}" for m in METHODS) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    out.write_text("\n".join(lines))
    return out


def write_pdf(sigmas, rows):
    """A single-page PDF with axes and three polylines, no libraries."""
    W, H = 360, 240
    L, R, T, B = 48, 12, 12, 36
    ymin, ymax = 20, 40
    def X(s): return L + (s - sigmas[0]) / (sigmas[-1] - sigmas[0]) * (W - L - R)
    def Y(v): return B + (v - ymin) / (ymax - ymin) * (H - T - B)
    ops = [f"0.6 w 0.35 0.35 0.35 RG {L} {B} m {W-R} {B} l S {L} {B} m {L} {H-T} l S"]
    ops.append("BT /F1 8 Tf 0.3 0.3 0.3 rg")
    for s in sigmas[::2]:
        ops.append(f"1 0 0 1 {X(s)-6:.1f} {B-12} Tm ({s:.1f}) Tj")
    for v in range(ymin, ymax + 1, 5):
        ops.append(f"1 0 0 1 {L-22} {Y(v)-3:.1f} Tm ({v}) Tj")
    ops.append(f"1 0 0 1 {W/2-18:.1f} {B-24} Tm (noise \\(sigma\\)) Tj")
    ops.append(f"1 0 0 1 {L+4} {H-T-10} Tm (PSNR, dB) Tj ET")
    styles = {"DPS": "0.45 0.45 0.5 RG 1 w", "Unanchored": "0.65 0.65 0.7 RG 1 w [3 2] 0 d", "Anchored": "0.66 0.2 0.18 RG 1.6 w"}
    for m, style in styles.items():
        pts = " ".join(f"{X(s):.1f} {Y(v):.1f} {'m' if i == 0 else 'l'}" for i, (s, v) in enumerate(zip(sigmas, rows[m])))
        ops.append(f"q {style} {pts} S Q")
    ops.append("BT /F1 8 Tf")
    for i, (m, style) in enumerate(styles.items()):
        rgb = style.split(" RG")[0]
        ops.append(f"{rgb} rg 1 0 0 1 {W-R-92} {H-T-14-i*11} Tm ({m}) Tj")
    ops.append("ET")
    stream = zlib.compress("\n".join(ops).encode())
    objs = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {W} {H}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>".encode(),
        b"<< /Length " + str(len(stream)).encode() + b" /Filter /FlateDecode >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, o in enumerate(objs, 1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + o + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objs)+1}\n0000000000 65535 f \n".encode()
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objs)+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    path = ROOT / "figures" / "psnr-vs-noise.pdf"
    path.write_bytes(out)
    return path


def main(sigma_max: float, seeds: int = 5):
    sigmas, rows = sweep(sigma_max, seeds)
    fig = write_pdf(sigmas, rows)
    tab = write_table(sigmas, rows)
    print(f"swept {len(sigmas)} noise levels x {seeds} seeds")
    print(f"wrote {fig.relative_to(ROOT)} and {tab.relative_to(ROOT)}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--sigma", type=float, default=0.3)
    p.add_argument("--seeds", type=int, default=5)
    a = p.parse_args()
    main(a.sigma, a.seeds)
