import { useRef, useState } from "react";
import { ChevronRight, FileText, BookMarked, Code2, Image, Database, File, Folder } from "lucide-react";
import type { Entry, Project } from "../lib/backend";
import type { OutlineItem } from "../lib/latex";

const ICON = { tex: FileText, bib: BookMarked, code: Code2, figure: Image, data: Database, other: File, dir: Folder } as const;

function Node({ entry, current, onSelect, depth }: { entry: Entry; current: string | null; onSelect: (p: string) => void; depth: number }) {
  const [open, setOpen] = useState(depth < 1);
  const Icon = ICON[entry.kind];
  const isDir = entry.kind === "dir";
  const onKey = (e: React.KeyboardEvent) => {
    if (!isDir) return;
    if (e.key === "ArrowRight" && !open) { e.preventDefault(); setOpen(true); }
    if (e.key === "ArrowLeft" && open) { e.preventDefault(); setOpen(false); }
  };
  return (
    <li role="treeitem" aria-level={depth + 1} aria-expanded={isDir ? open : undefined} aria-selected={current === entry.path}>
      <button
        className="tree-row" tabIndex={-1}
        aria-current={!isDir && current === entry.path ? "true" : undefined}
        onClick={() => (isDir ? setOpen((o) => !o) : onSelect(entry.path))}
        onKeyDown={onKey}
      >
        {isDir ? <ChevronRight className={`chev ${open ? "open" : ""}`} aria-hidden /> : <span style={{ width: 12 }} />}
        <Icon aria-hidden />
        <span className="label">{entry.name}</span>
      </button>
      {isDir && open && (
        <ul role="group">
          {entry.children.map((c) => <Node key={c.path} entry={c} current={current} onSelect={onSelect} depth={depth + 1} />)}
        </ul>
      )}
    </li>
  );
}

function countFiles(entries: Entry[]): number {
  return entries.reduce((n, e) => n + (e.kind === "dir" ? countFiles(e.children) : 1), 0);
}

interface Props {
  project: Project | null;
  current: string | null;
  outline: OutlineItem[];
  onSelect: (path: string) => void;
  onJump: (line: number) => void;
}

export function Navigator({ project, current, outline, onSelect, onJump }: Props) {
  const ref = useRef<HTMLElement>(null);

  // Up and down move between rows in the whole navigator; left and right are handled by folders.
  const onKey = (e: React.KeyboardEvent) => {
    if (e.key !== "ArrowDown" && e.key !== "ArrowUp") return;
    const rows = Array.from(ref.current?.querySelectorAll<HTMLButtonElement>(".tree-row, .outline-row") ?? []);
    const i = rows.indexOf(document.activeElement as HTMLButtonElement);
    const next = rows[i + (e.key === "ArrowDown" ? 1 : -1)];
    if (next) { e.preventDefault(); next.focus(); }
  };

  if (!project) {
    return (
      <aside className="navigator" ref={ref}>
        <div className="empty-nav">
          <strong>No paper open</strong>
          Open a folder that contains your manuscript and its code. Dabir reads it in place and changes nothing.
        </div>
      </aside>
    );
  }
  return (
    <aside className="navigator" ref={ref} onKeyDown={onKey}>
      <section className="nav-section">
        <div className="nav-heading"><span>Files</span><span className="count">{countFiles(project.tree)}</span></div>
        <ul className="tree" role="tree" aria-label="Project files" tabIndex={0}
          onFocus={(e) => { if (e.target === e.currentTarget) e.currentTarget.querySelector<HTMLButtonElement>('.tree-row[aria-current="true"], .tree-row')?.focus(); }}>
          {project.tree.map((e) => <Node key={e.path} entry={e} current={current} onSelect={onSelect} depth={0} />)}
        </ul>
      </section>

      {outline.length > 0 && (
        <section className="nav-section">
          <div className="nav-heading"><span>Outline</span></div>
          {outline.map((o) => (
            <button key={`${o.number}-${o.line}`} className={`outline-row l${o.level}`} onClick={() => onJump(o.line)} title={`Line ${o.line}`}>
              <span className="num">{o.number}</span>
              <span>{o.text}</span>
            </button>
          ))}
        </section>
      )}

      <section className="nav-section">
        <div className="nav-heading">
          <span>Changes<span className="sample-tag" title="Real Git status arrives in phase 2">sample</span></span>
          <span className="count">{project.hasGit ? "on main" : "no git"}</span>
        </div>
        {project.hasGit ? (
          <div className="changes">
            <div className="change">
              <span className="file">figures/psnr-vs-noise.pdf</span>
              <span className="meta"><span>regenerated by agent</span><span className="stat"><span className="add">binary</span></span></span>
            </div>
            <div className="change">
              <span className="file">main.tex</span>
              <span className="meta"><span>you, unsaved</span><span className="stat"><span className="add">+6</span><span className="del">−4</span></span></span>
            </div>
          </div>
        ) : (
          <div className="empty-nav">This folder is not a Git repository yet. Dabir can initialise one when you make your first change.</div>
        )}
      </section>
    </aside>
  );
}
