import { useState } from "react";
import { ChevronRight, FileText, BookMarked, Code2, Image, Database, File, Folder } from "lucide-react";
import type { Entry, Project } from "../lib/backend";
import type { OutlineItem } from "../lib/latex";

const ICON = { tex: FileText, bib: BookMarked, code: Code2, figure: Image, data: Database, other: File, dir: Folder } as const;

function Node({ entry, current, onSelect, depth }: { entry: Entry; current: string | null; onSelect: (p: string) => void; depth: number }) {
  const [open, setOpen] = useState(depth < 1);
  const Icon = ICON[entry.kind];
  if (entry.kind === "dir") {
    return (
      <li>
        <button className="tree-row" onClick={() => setOpen((o) => !o)} aria-expanded={open}>
          <ChevronRight className={`chev ${open ? "open" : ""}`} />
          <Icon />
          <span className="label">{entry.name}</span>
        </button>
        {open && (
          <ul>
            {entry.children.map((c) => <Node key={c.path} entry={c} current={current} onSelect={onSelect} depth={depth + 1} />)}
          </ul>
        )}
      </li>
    );
  }
  return (
    <li>
      <button className="tree-row" aria-current={current === entry.path ? "true" : undefined} onClick={() => onSelect(entry.path)}>
        <span style={{ width: 12 }} />
        <Icon />
        <span className="label">{entry.name}</span>
      </button>
    </li>
  );
}

function countFiles(entries: Entry[]): number {
  return entries.reduce((n, e) => n + (e.kind === "dir" ? countFiles(e.children) : 1), 0);
}

interface Props {
  project: Project | null;
  current: string | null;
  outline: OutlineItem[];
  onSelect: (path: string) => void;
  onJump: (line: number) => void;
}

export function Navigator({ project, current, outline, onSelect, onJump }: Props) {
  if (!project) {
    return (
      <aside className="navigator">
        <div className="empty-nav">
          <strong>No paper open</strong>
          Open a folder that contains your manuscript and its code. Dabir reads it in place and changes nothing.
        </div>
      </aside>
    );
  }
  return (
    <aside className="navigator">
      <section className="nav-section">
        <div className="nav-heading"><span>Files</span><span className="count">{countFiles(project.tree)}</span></div>
        <ul className="tree">
          {project.tree.map((e) => <Node key={e.path} entry={e} current={current} onSelect={onSelect} depth={0} />)}
        </ul>
      </section>

      {outline.length > 0 && (
        <section className="nav-section">
          <div className="nav-heading"><span>Outline</span></div>
          {outline.map((o) => (
            <button key={`${o.number}-${o.line}`} className={`outline-row l${o.level}`} onClick={() => onJump(o.line)}>
              <span className="num">{o.number}</span>
              <span>{o.text}</span>
            </button>
          ))}
        </section>
      )}

      <section className="nav-section">
        <div className="nav-heading"><span>Changes</span><span className="count">{project.hasGit ? "on main" : "no git"}</span></div>
        {project.hasGit ? (
          <div className="changes">
            <div className="change">
              <span className="file">figures/psnr-vs-noise.pdf</span>
              <span className="who">regenerated by agent</span>
              <span className="stat"><span className="add">bin</span></span>
            </div>
            <div className="change">
              <span className="file">main.tex</span>
              <span className="who">you, unsaved</span>
              <span className="stat"><span className="add">+6</span><span className="del">−4</span></span>
            </div>
          </div>
        ) : (
          <div className="empty-nav">This folder is not a Git repository yet. Dabir can initialise one when you make your first change.</div>
        )}
      </section>
    </aside>
  );
}
